INSERT INTO safety_classifications (classification_code, classification_name, regulatory_basis, qa_requirements, description)
VALUES ('SR','Safety-Related','10CFR50 Appendix B','Full 10CFR50 Appendix B quality assurance program including controlled procurement, receipt inspection, dedicated storage, qualified personnel, documented maintenance and calibration procedures, independent verification, and auditable records.', 'Structures, systems, and components that are relied upon to remain functional during and following design basis events to ensure the integrity of the reactor coolant pressure boundary, the capability to shut down the reactor and maintain it in a safe shutdown condition, and the capability to prevent or mitigate the consequences of accidents that could result in potential offsite exposures.');

INSERT INTO safety_classifications (classification_code, classification_name, regulatory_basis, qa_requirements, description)
VALUES ('AQ','Augmented Quality','10CFR50.65 Maintenance Rule, plant administrative procedures','Enhanced quality controls beyond commercial grade but not the full scope of 10CFR50 Appendix B. Includes controlled maintenance procedures, periodic calibration, and documented work history.', 'Equipment that is important to safety but does not meet the full definition of safety-related. Includes equipment relied upon to mitigate accidents or transients, support emergency operating procedures, or monitor post-accident conditions. Subject to enhanced quality controls beyond commercial grade.');

INSERT INTO safety_classifications (classification_code, classification_name, regulatory_basis, qa_requirements, description)
VALUES ('NSR','Non-Safety Related','Plant administrative procedures, industry standards','Commercial grade quality practices. Maintenance and calibration performed per manufacturer recommendations and plant procedures. Work history documented but not subject to independent verification requirements.','Balance of plant instrumentation that does not perform a safety function. Failure does not prevent safe shutdown or mitigate accident consequences. Maintained for operational efficiency, equipment protection, and regulatory compliance with non-safety requirements.');

INSERT INTO safety_classifications (classification_code, classification_name, regulatory_basis, qa_requirements, description)
VALUES ('IE','Important to Safety (Environmental)','10CFR50.49','Must be environmentally qualified to function under design basis accident conditions including temperature, pressure, radiation, humidity, and chemical spray. Requires EQ documentation package, periodic surveillance, and replacement before qualified life expiration.','Instruments required to function in harsh environments during and following design basis accidents. Must demonstrate operability under the temperature, pressure, radiation, steam, and chemical spray conditions postulated for the specific location. Subject to the Environmental Qualification program per 10CFR50.49.');

